### ISSUE TITLE
Unit of stress for training

### ISSUE THREAD

**Issue by JonathanSchmidt1** [materialsvirtuallab/m3gnet#2]
First of all thank you for the great repository.
We wanted to try some transfer learning from your original model and were wondering what the actual units of the stress data you have and we have are. Because vasp normally outputs stress in kbar = 0.1 GPa and if we understand the code correctly you convert the stress output of the model from eV/A^3 to GPa . Consequently, the training stress data should be multiplied by -0.1 but in your documentation you write multiply by -1. We also confirmed for some structures of mp-1168  that the stress values in your dataset are in KBar by repeating the calculation (although we were not able to reproduce the calculation for the first structure in the list, we get quite different forces and stresses for this structure).
Thank you very much for your help.

**Comment by chc273** [comment]
@JonathanSchmidt1  

It is indeed multiplying by `-0.1` I wanted to stress that it is in fact the negative of the VASP output stress, but I forgot to mention about the unit conversion. I have corrected the documentation. Thanks

**Comment by JonathanSchmidt1** [comment]
Great. Thank you for the quick response.
