### ISSUE TITLE
Reason for small training data?

### ISSUE THREAD

**Issue by janosh** [materialsvirtuallab/m3gnet#20]
Quoting from the paper:

> Our initial dataset comprises a sampling of the energies, forces and stresses from the first and middle ionic steps of the first relaxation and the last step of the second relaxation for calculations in the Materials Project database that contains “GGA Structure Optimization” or “GGA+U Structure Optimization” task types as of Feb 8, 2021. [...] In total, this “MPF.2021.2.8” dataset contains 187,687 ionic steps of 62,783 compounds, ...

What's the reason for not using the relaxation trajectories for all of the ~140 k MP structures?

**Comment by janosh** [comment]
Btw, in case others encounter this problem, I was getting strange errors trying to view or save the [data on figshare](https://figshare.com/articles/dataset/MPF_2021_2_8/19470599) which raised

```py
AttributeError: 'Lattice' object has no attribute '_pbc'
```

Maybe due to the fact the structures were pickled and `pymatgen` had a breaking change in the meantime?

Anyway, doing

```py
for structs in df.structure:
    for struct in structs:
        struct.lattice._pbc = (True, True, True)
```

solved the problem.

**Comment by chc273** [comment]
Several reasons, 1) the original documents have other formats. When we query using the methods described, this is a subset of the data we got. I believe this subset is more self-consistent than with the rest. 2) Training capability. I was using a single GPU for the training; the current data is already pushing the limit for me at least. 3) I believe that there isn't much more to add to the model if adding more data. I recently tested the hypothesis, and it seems that adding those additional data did not really help, and even make model worse (much higher energy and force errors). This also points to the data consistency concern in 1). 

Thanks for pointing out the pickle file issue. I will try to fix that soon.

**Comment by janosh** [comment]
Thanks for the detailed reply. By "original documents", do you mean older calculations on MP? Pre-dating a certain database version?

Also, do you have the formation energies for the 63k compounds you trained on? If you're going to update the figshare data, would it be possible to include those?

**Comment by chc273** [comment]
I have updated the data file and converted all structures into `cif`.

The formation energy can be directly calculated using the energies and structures. 1) construct a pymatgen entry using the structure and total energy, 2) construct a PhaseDiagram object. 3) calculate the formation energy using the phase diagram. One relevant example is here

https://github.com/materialsvirtuallab/Data-driven-First-Principles-Methods-for-the-Study-and-Design-of-Alkali-Superionic-Conductors/blob/master/notebooks/2%20-%20Phase%20and%20Electrochemical%20Stability.ipynb

**Comment by janosh** [comment]
> I have updated the data file and converted all structures into `cif`.

Thanks!

> The formation energy can be directly calculated using the energies and structures.

That's what I did but wanted to be sure they're consistent with yours since I used the [new `PatchedPhaseDiagram`](https://github.com/materialsproject/pymatgen/pull/2283) that was recently added to `pymatgen`. No worries though, I'll redo with the regular `PhaseDiagram`.

**Comment by janosh** [comment]
Btw, in the example you linked, I know repeated processing is a no-op but might still be confusing to readers that `entry` is processed twice. Maybe this would be better:

```diff py
compatibility = MaterialsProjectCompatibility()
entry = compatibility.process_entry(entry)
- entries = compatibility.process_entries([entry] + mp_entries + lpo_entries)
+ entries = [entry] + compatibility.process_entries(mp_entries + lpo_entries)
```
