### ISSUE TITLE
Hyperparameters for benchmark on IAP dataset

### ISSUE THREAD

**Issue by lan496** [materialsvirtuallab/m3gnet#30]
I am trying to reproduce the results of ["A Universal Graph Deep Learning Interatomic Potential for the Periodic Table."](https://arxiv.org/abs/2202.02450) at [my repository](https://github.com/lan496/torch-m3gnet). Hyperparameters to train M3GNet on the MPF2021.2.8 dataset are shown in [pretrained/MP-2021.2.8-EFS/m3gnet.json](https://github.com/materialsvirtuallab/m3gnet/blob/main/pretrained/MP-2021.2.8-EFS/m3gnet.json).
Then, which hyperparameters should I choose to reproduce the benchmark on the IAP dataset (Table 1)?

**Comment by chc273** [comment]
The parameters should be the same

**Comment by lan496** [comment]
Thanks for your quick reply!
