### ISSUE TITLE
default stress_weight in M3GNetCalculator 1.0 -> 0.00624?

### ISSUE THREAD

**Issue by mhellstr** [materialsvirtuallab/m3gnet#31]
Relaxer has a default stress_weight of 0.01. If the m3gnet model predicts stresses in GPa, shouldn't the conversion factor from GPa to eV/ang^3 (ASE unit) be used instead? So stress_weight =  0.0062415? If I use this number I get much better agreement to numerically calculated stress tensors. 

Actually that should probably be the default stress_weight in M3GNetCalculator (where it's currently 1.0), so that it's used also by MolecularDynamics?

In the ideal case the stress_weight would be stored inside the Potential when training.

**Comment by chc273** [comment]
In relaxer the weight was just a factor to tune relative importance of cell relax and coordinates relax. In MD it has to be exact. However I have not personally tried the NPT ensemble that requires stress

**Comment by mhellstr** [comment]
Thanks, the below lines in M3GNetCalculator lead me to believe that stress_weight is just unit conversion?

>         if self.compute_stress:
>             self.results.update(stress=results[2].numpy()[0] * self.stress_weight)
