### ISSUE TITLE
Energy as an array in M3GNetCalculator

### ISSUE THREAD

**Issue by gpetretto** [materialsvirtuallab/m3gnet#32]
While using a postprocessing tool from ASE after a calculation with the M3GNetCalculator (a NEB plot) I got an error due to the fact that the M3GNetCalculator sets the  `energy` as a numpy array with one element, rather than a simple float https://github.com/materialsvirtuallab/m3gnet/blob/cd2aeb30f701c135c352e4c3b7cc216352b4a124/m3gnet/models/_dynamics.py#L88 
I can fix the problem in some way when doing the postprocess, but since other ASE calculators usually return a float there, I wanted to check if this is a specific choice for the M3GNetCalculator or if it is a bug.

**Comment by chc273** [comment]
Hi @gpetretto, it was not a specific consideration in this case. m3gnet models output arrays and it was working with relaxer and MD.

**Comment by gpetretto** [comment]
Hi @chc273, thanks for the reply. If this is not a requirement, would you agree to have it as a float then? I can open a PR if you prefer.

**Comment by chc273** [comment]
@gpetretto yes thanks. Also please make sure MD and relaxation after the change run as expected.
