### ISSUE TITLE
Get energy above hull through the m3gnet model

### ISSUE THREAD

**Issue by Mycroft2333** [materialsvirtuallab/m3gnet#39]
Hi~
I noticed on matterverse.ai that the data for *energy above hull* can be obtained through the *m3gnet vmatbench_0.0.1.0* model. Could you please share the code of the example?
Thanks

**Comment by shyuep** [comment]
For this, all you need to do is to query for all entries in the Materials Project in the same chemical system, make an entry using the m3gnet relaxed structure and energy, and then construct a phase diagram.
