### ISSUE TITLE
fix atoms during MD/relax

### ISSUE THREAD

**Issue by negf** [materialsvirtuallab/m3gnet#56]
Hi,

Is it possible to fix some atoms during MD/relax runs ?

**Comment by shyuep** [comment]
The MD is controlled by ASE. So you can check what parameters need to be passed to fix atoms. Maybe some editing of the code might be needed.

**Comment by negf** [comment]
Thanks.  Indeed it was enough to set pymatgen atoms.constraints which supports ASE FixAtoms.
