### ISSUE TITLE
Feasible to have this packaged on Anaconda?

### ISSUE THREAD

**Issue by sgbaird** [materialsvirtuallab/m3gnet#8]
Otherwise, I'll probably be making my own port of it on conda-forge since I'm planning to package this as a dependency for [`xtal2png`](https://github.com/sparks-baird/xtal2png) and all deps for conda-forge packages have to also be packaged on conda-forge IIUC.

Btw, very nice and timely package! I had been hoping for something like this for a while now. Even saw and starred `m3gnet` a little while ago, but didn't realize it's an easy-to-use drop-in DFT relaxation surrogate until I read:
> One of the key accomplishments of M3GNet is the development of a universal IAP that can work across the entire periodic table of the elements by training on relaxations performed in the [Materials Project](http://materialsproject.org/).

Just a passing suggestion and feel free to ignore: might be worth adding something related to this to the description:

![image](https://user-images.githubusercontent.com/45469701/174191241-49e222b1-84e4-4a36-8f82-cc45c1fc889b.png)

Maybe:
> Materials graph network with 3-body interactions featuring a DFT surrogate crystal relaxer and a state-of-the-art property predictor.

or something similar.

Excited to try it out and incorporate it as a post-processing step into xtal2png!

**Comment by shyuep** [comment]
The conda tests now all pass (no windows). So it is now just a matter of TPTB merging it.

**Comment by sgbaird** [comment]
Unfortunately, I do most of my development on Windows, with WSL2 as a backup and HPC remoting, these days via VS Code ssh, as a 2nd backup. I've thought about switching to Linux for a few years (which honestly would be a big relief), but have somehow held out with the idea of "I'll represent other Windows users and work out the kinks in things". Excuse the meta-commentary I'm finally getting off my chest 😅😌. Maybe I'll finally make the switch.

For now, I think I'll just write some Windows-specific instructions in my README and raise an `ImportError` with a suggestion to `pip install m3gnet` in case someone misses the note in the README.

@shyuep Thanks so much for putting this together on such short notice and for helping with the other issues!

**Comment by shyuep** [comment]
I see... well, if you figure out how to get it to work on Windows, you can let me know. I don't have a Windows machine so I can't really test it (not to mention that I have not touched Windows in more than a decade). I am actually not fully sure why Windows conda make is failing. It might be tensorflow (a major culprit) or it might be something else.
